version: "3"

services:
  
    postgres:
        image: postgres:9.6
        restart: always
        ports:
          - 5432:5432
        environment:
          POSTGRES_PASSWORD: root
    
    pgadmin:
        image: dpage/pgadmin4
        environment:
          PGADMIN_DEFAULT_EMAIL: "admin@gmail.com"
          PGADMIN_DEFAULT_PASSWORD: "admin"
        ports:
          - "16543:80"
        depends_on:
          - postgres